name: Set DEFAULT_JAVA_VERSION
description: Set DEFAULT_JAVA_VERSION from various places

outputs:
  version:
    description: Java version
    value: ${{steps.result.outputs.version}}

runs:
  using: composite
  steps:
  - name: Read Gradle Daemon Java version
    id: daemon-java-version
    uses: remal-github-actions/read-property@v1
    with:
      file: gradle/gradle-daemon-jvm.properties
      property: 'toolchainVersion'
      failIfFileNotFound: 'false'
      failIfPropertyNotFound: 'false'

  - name: Read build Java version
    if: ${{steps.daemon-java-version.outputs.value == ''}}
    id: build-java-version
    uses: remal-github-actions/read-property@v1
    with:
      file: gradle.properties
      property: 'java-build.version'
      failIfFileNotFound: 'false'
      failIfPropertyNotFound: 'false'

  - name: Retrieve max tested versions
    if: ${{true || steps.build-java-version.outputs.value == '' && steps.daemon-java-version.outputs.value == ''}}
    id: max-java-version-matrix
    uses: remal-github-actions/matrix-versions@v1
    with:
      matrix: |
        java:
          dependency: java
          only:
          - once
          - lts
          - stable
          include:
          - '(,25)'

  - name: Compose result
    id: result
    shell: bash
    env:
      RESULT_VERSION: ${{
        steps.daemon-java-version.outputs.value
        || steps.build-java-version.outputs.value
        || steps.max-java-version-matrix.outputs.allMatrixIncludes && fromJSON(steps.max-java-version-matrix.outputs.allMatrixIncludes)[0].java
        }}
    run: |
      echo "DEFAULT_JAVA_VERSION=$RESULT_VERSION" | tee -a $GITHUB_ENV
      echo "version=$RESULT_VERSION" >> $GITHUB_OUTPUT
