#!/usr/bin/env bash

PWD=$(pwd)
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && $PWD )
if [ "$SCRIPT_DIR" == "$PWD" ]; then
    SCRIPT_DIR="."
fi

"$SCRIPT_DIR/retry-connection-timeouts" "$SCRIPT_DIR/gradlew" "$@"
