#!/usr/bin/env bash

DELAY_INTERVAL=1

HIGHLIGHT_COLOR='\033[1;33m'
TRACE_COLOR='\033[1;90m'
NO_COLOR='\033[0m'

RESULT=0

for ATTEMPT in $(seq 1 3); do
    if [ "$ATTEMPT" -gt 1 ]; then
        echo -e "\n\n${HIGHLIGHT_COLOR}Waiting $DELAY_INTERVAL seconds before attempt #$ATTEMPT...${NO_COLOR}\n\n"
        sleep "$DELAY_INTERVAL"
    fi

    LOGFILE=$(mktemp)
    echo -e "${TRACE_COLOR}Storing console output of $* in log file $LOGFILE${NO_COLOR}"

    "$@" |& tee "$LOGFILE"
    RESULT="${PIPESTATUS[0]}"

    if [ "$RESULT" -eq 0 ]; then
        exit 0

    elif STR="Could not HEAD" && grep -q "\b$STR\b" "$LOGFILE"; then
        echo "::warning::'$STR' found in log file $LOGFILE, retrying"

    elif STR="connect timed out" && grep -q "\b$STR\b" "$LOGFILE"; then
        echo "::warning::'$STR' found in log file $LOGFILE, retrying"

    elif STR="oblem occurred evaluating root project" && grep -q "\b$STR\b" "$LOGFILE"; then
        echo "::warning::'$STR' found in log file $LOGFILE, retrying"

    else
        break
    fi
done

exit "$RESULT"
